### ISSUE TITLE
Version 0.19.0 does not compile on Mac 12.1 (non-M1)

### ISSUE THREAD

**Issue by nterol** [project-serum/anchor#1181]
Hello !
I tried to install anchor 0.19.0 by using this command: 
`cargo install --git https://github.com/project-serum/anchor --tag v0.19.0 anchor-cli --locked`

But I got these errors : 

```bash
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /Users/mycomputername/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: use of unstable library feature 'osstring_ascii'
   --> /Users/mycomputername/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
    |
130 |                 v.eq_ignore_ascii_case(val)
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information

error: aborting due to 2 previous errors
```

Installing version 0.18.2 works just fine. 

I am under Mac OSX 12.1 (not M1). 
rustc version is `rustc 1.57.0 (f1edd0429 2021-11-29)`
rustup version is `rustup 1.24.3 (ce5817a94 2021-05-31)`
solana version is `solana-cli 1.9.1 (src:b66e2ae3; feat:4100269022)`

**Comment by paul-schaaf** [comment]
have you installed the nightly rust channel?

**Comment by nterol** [comment]
No, I'll try it

**Comment by wd255** [comment]
Thanks @paul-schaaf Tried and installing nightly rust worked.
